---
- hosts: 172.31.34.180
  become: yes
  tasks: 
  - name: create a file
    file: 
      path: /home/ubuntu/myfile
      state: touch

  - name: install apache2
    apt:
      name: apache2
      state: present
    notify: startwebserver

  - name: copy a file
    copy:
      src: mytextfile
      dest: /var/www/html/index.html

  - name: copy dynamic files
    template:
       src: mydynamicfile.j2
       dest: /var/www/html/index.html
    notify: startwebserver

  - name: download remote files
    get_url: 
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
        force_basic_auth: yes

  handlers:
  - name: startwebserver
    service:
       name: apache2
       state: restarted      