---
- hosts: myWebServers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install webserver on ubantu ansible nodes
    apt:
     name: "{{mywebpackonubantu}}"
     state: present
    when: ansible_os_family== "Debian" 

  - name: i want to start webserver on ubantu ansible nodes
    service:
     name: "{{mywebpackonubantu}}"
     state: started
    when: ansible_os_family== "Debian" 

  - name: i want to install webserver on redhat ansible nodes
    yum:
     name: "{{mywebpackonredhat}}"
     state: present
    when: ansible_os_family== "RedHat"

  - name: i want to start webserver on redhat ansible nodes
    service:
     name: "{{mywebpackonredhat}}"
     state: started
    when: ansible_os_family== "RedHat"  

 